//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// HFCommClient.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDR_MAINFRAME                   128
#define IDD_CLIENT_SAMPLE_DIALOG        134
#define IDD_INDEX_FUT_SISE_DLG          135
#define IDD_STOCK_SISE_DLG              136
#define IDD_INDEX_OPT_SISE_DLG          137
#define IDD_FOREIGN_FUT_SISE_DLG        138
#define IDD_FX_SISE_DLG                 139
#define IDD_CME_FUT_SISE_DLG            140
#define IDD_EUREX_OPT_SISE_DLG          141
#define IDD_FFUT_ORD_DLG                142
#define IDD_INDEX_FUT_ORD_DLG           143
#define IDD_CME_EU_ORD_DLG              144
#define IDD_FX_ORD_DLG                  145
#define IDD_SISE_INDUSTRY_INDEX_DLG     146
#define IDD_STOCK_ORD_DLG               148
#define ID_LOGIN                        1000
#define ID_LOGOUT                       1001
#define IDC_RQTEST                      1002
#define IDC_SBTEST                      1003
#define IDC_SBREMOVE                    1004
#define IDC_TRCODE                      1005
#define IDC_INPUTTEXT                   1006
#define IDC_OUTPUT                      1007
#define IDC_ALL_SBREMOVE                1008
#define IDC_HFCOMMAGENTCTRL2            1011
#define IDC_HFCOMMAGENTCTRL1            1013
#define IDC_JONGMOK                     1014
#define IDC_GUBUN                       1015
#define IDC_INITCOMM                    1016
#define IDC_TERMINATE                   1017
#define IDC_EDIT_ID                     1018
#define IDC_EDIT_PWD                    1019
#define IDC_EDIT3                       1020
#define IDC_EDIT_AUTH_PWD               1020
#define IDC_BTN_FID_TEST                1021
#define IDC_BTN_NEXT                    1022
#define IDC_BTN_PREV                    1023
#define IDC_BTN_FID_S_TEST              1024
#define IDC_EDIT1                       1025
#define IDC_EDIT_CHART_CNT              1025
#define IDC_EDIT_DEPOSIT                1025
#define IDC_CHECK_DEMO                  1026
#define IDC_CMB_ACCNO                   1027
#define IDC_EDIT2                       1028
#define IDC_EDIT_IP                     1028
#define IDC_COMM_STATUS                 1029
#define IDC_SELL_1                      1030
#define IDC_SELL_2                      1031
#define IDC_SELL_3                      1032
#define IDC_SELL_4                      1033
#define IDC_SELL_5                      1034
#define IDC_BUY_1                       1035
#define IDC_BUY_2                       1036
#define IDC_BUY_3                       1037
#define IDC_BUY_4                       1038
#define IDC_BUY_5                       1039
#define IDC_SELL_REMAIN_1               1040
#define IDC_SELL_REMAIN_2               1041
#define IDC_SELL_REMAIN_3               1042
#define IDC_SELL_REMAIN_4               1043
#define IDC_SELL_REMAIN_5               1044
#define IDC_BUY_REMAIN_1                1045
#define IDC_BUY_REMAIN_2                1046
#define IDC_BUY_REMAIN_3                1047
#define IDC_BUY_REMAIN_4                1048
#define IDC_BUY_REMAIN_5                1049
#define IDC_EDIT_SYMBOL                 1050
#define IDC_BUTTON1                     1051
#define IDC_BTN_REQ_HOGA                1051
#define IDC_BTN_INDEX_FUT_SISE          1051
#define IDC_BTN_SELL                    1051
#define IDC_SYMBOL_NAME                 1052
#define IDC_BTN_INDEX_OPT_SISE          1052
#define IDC_BTN_BUY                     1052
#define IDC_EDIT_SYMBOL_PRICE           1053
#define IDC_BTN_FOREIGN_FUT_SISE        1053
#define IDC_BTN_CHANGE                  1053
#define IDC_BTN_REQ_PRICE               1054
#define IDC_BTN_FX_MARGIN_SISE          1054
#define IDC_BTN_CANCEL                  1054
#define IDC_CUR_PRICE                   1055
#define IDC_BTN_CME_FUT_SISE            1055
#define IDC_BTN_CLOSE                   1055
#define IDC_START_PRICE                 1056
#define IDC_BTN_EUREX_OPT_SISE          1056
#define IDC_BTN_MODSL                   1056
#define IDC_HIGH_PRICE                  1057
#define IDC_BTN_CALSL                   1057
#define IDC_BTN_WEEKLY_SISE             1057
#define IDC_LOW_PRICE                   1058
#define IDC_BTN_INDUSTRY_INDEX_SISE2    1058
#define IDC_VOLUME                      1059
#define IDC_DIFF                        1060
#define IDC_DIFF_SIGN                   1061
#define IDC_DIFF_RATE                   1062
#define IDC_PREV_VOLUME                 1063
#define IDC_SYMBOL_NAME_PRICE           1064
#define IDC_EDIT_SYMBOL_TICK            1065
#define IDC_EDIT_SYMBOL_ORD             1065
#define IDC_BTN_REQ_TICK                1066
#define IDC_EDIT_ORD_PRC                1066
#define IDC_LIST_TICK                   1067
#define IDC_EDIT_ORD_VOL                1067
#define IDC_SYMBOL_NAME_TICK            1068
#define IDC_EDIT_ORG_NO                 1068
#define IDC_BTN_REQ_TICK_NEXT           1069
#define IDC_BTN_REQ_EXEC_LIST           1069
#define IDC_API_AGENT_PATH              1070
#define IDC_LIST_SYMBOL                 1071
#define IDC_LIST_ORD                    1071
#define IDC_BTN_REQ_CODE_LIST           1072
#define IDC_BTN_REQ_EXEC_LIST_NEXT      1072
#define IDC_BTN_REQ_CODE_LIST_NEXT      1073
#define IDC_BTN_REQ_BALANCE             1073
#define IDC_SELL_CNT1                   1074
#define IDC_LIST_BALANCE                1074
#define IDC_SELL_CNT2                   1075
#define IDC_BTN_REQ_BALANCE_NEXT        1075
#define IDC_SELL_CNT3                   1076
#define IDC_LIST_ACCNO                  1076
#define IDC_SELL_CNT4                   1077
#define IDC_BTN_REQ_DEPOSIT             1077
#define IDC_SELL_CNT5                   1078
#define IDC_LIST_DEPOSIT                1078
#define IDC_BUY_CNT1                    1079
#define IDC_BTN_REQ_DEPOSIT_NEXT        1079
#define IDC_BUY_CNT2                    1080
#define IDC_BTN_REQ_NON_EXEC_LIST       1080
#define IDC_BUY_CNT3                    1081
#define IDC_LIST_NON_EXE                1081
#define IDC_BUY_CNT4                    1082
#define IDC_BTN_REQ_NON_EXEC_LIST_NEXT  1082
#define IDC_BUY_CNT5                    1083
#define IDC_BUY_REMAIN_10               1083
#define IDC_EDIT_STOP_PRC               1083
#define IDC_LOGIN_STATE                 1084
#define IDC_BTN_STOCK_SISE              1085
#define IDC_EDIT_SYMBOL_CHART           1085
#define IDC_LIST_REAL                   1085
#define IDC_CHK_AUTO_REQ                1086
#define IDC_LIST_SYMBOL2                1086
#define IDC_BTN_REQ_CHART               1087
#define IDC_EDIT_SYMBOL_HOUSE           1087
#define IDC_SYMBOL_NAME_CHART           1088
#define IDC_EDIT_LIMIT_PRC              1088
#define IDC_BTN_REQ_PORTFOLIO           1089
#define IDC_EDIT_T_STOP_PRC             1089
#define IDC_BTN_REQ_CODE_LIST2          1089
#define IDC_LIST_CHART                  1090
#define IDC_CHK_AUTO_REQ_CHART          1091
#define IDC_RADIO_TICK                  1092
#define IDC_RADIO_MIN                   1093
#define IDC_RADIO_DAY                   1094
#define IDC_RADIO_WEEK                  1095
#define IDC_RADIO_MON                   1096
#define IDC_BTN_REQ_CHART_NEXT          1097
#define IDC_LIST_CHART2                 1098
#define IDC_LIST_PORTFOLIO              1098
#define IDC_BTN_REQ_CODE_LIST_NEXT2     1098
#define IDC_DATETIME_FROM               1099
#define IDC_DATETIME_TO                 1100
#define IDC_STATIC_CHART                1101
#define IDC_CUR_SELL                    1102
#define IDC_CUR_BUY                     1103
#define IDC_SPREAD                      1104
#define IDC_PIP_COST                    1105
#define IDC_SELL_INST                   1106
#define IDC_BUY_INST                    1107
#define IDC_EDIT_PORT_OUT_FID1          1108
#define IDC_EDIT_PORT_OUT_FID2          1109
#define IDC_EDIT_PORT_OUT_FID3          1110
#define IDC_EDIT_PORT_OUT_FID4          1111
#define IDC_EDIT_PORT_OUT_FID5          1112
#define IDC_EDIT_PORT_VALUE1            1113
#define IDC_EDIT_PORT_VALUE2            1114
#define IDC_EDIT_PORT_VALUE3            1115
#define IDC_EDIT_PORT_VALUE4            1116
#define IDC_EDIT_PORT_VALUE5            1117
#define IDC_EDIT_MARKET_CODE1           1118
#define IDC_EDIT_MARKET_CODE2           1119
#define IDC_EDIT_MARKET_CODE3           1120
#define IDC_EDIT_MARKET_CODE4           1121
#define IDC_EDIT_MARKET_CODE5           1122
#define IDC_OUT_FID1                    1123
#define IDC_OUT_FID2                    1124
#define IDC_OUT_FID3                    1125
#define IDC_OUT_FID4                    1126
#define IDC_OUT_FID5                    1127
#define IDC_OUT_VALUE1                  1128
#define IDC_OUT_VALUE2                  1129
#define IDC_OUT_VALUE3                  1130
#define IDC_OUT_VALUE4                  1131
#define IDC_CHECK1                      1131
#define IDC_CHK_AllQty                  1131
#define IDC_CHECK_JF                    1131
#define IDC_OUT_VALUE5                  1132
#define IDC_CMB_ORD_TYPE                1132
#define IDC_EDIT_ACC_PWD                1133
#define IDC_BTN_FFORD                   1134
#define IDC_CMB_ORD_COND                1134
#define IDC_BTN_INDEXFORD               1135
#define IDC_BTN_REQ_ACCNO               1136
#define IDC_BTN_CMEEUFORD               1136
#define IDC_BTN_REQ_ACCNO2              1137
#define IDC_BTN_LOAD_USER_ACC           1137
#define IDC_BTN_FXORD                   1137
#define IDC_EDIT_ACCNO                  1138
#define IDC_BTN_STKORD                  1138
#define IDC_EDIT_APNO                   1139
#define IDC_CON_REAL                    1140
#define IDC_CON_DEMO                    1141
#define IDC_CON_F_DEMO                  1142
#define IDC_TRAN_MSG                    1143
#define IDC_ORDER_NO                    1144
#define IDC_DATETIME1                   1145
#define IDC_EVL_DPST_TOT_AMT            1146
#define IDC_DATETIME_N1                 1146
#define IDC_EVL_DPST_CSH                1147
#define IDC_DATETIME_N2                 1147
#define IDC_DPST_TOT_AMT                1148
#define IDC_DATETIME_E1                 1148
#define IDC_DPST_CSH                    1149
#define IDC_DATETIME_E2                 1149
#define IDC_DPST_SBST                   1150
#define IDC_WDRW_PSBL_TOT_AMT           1151
#define IDC_WDRW_PSBL_CSH               1152
#define IDC_WDRW_PSBL_SBST_AMT          1153
#define IDC_ORDR_PSBL_TOT_AMT           1154
#define IDC_ORDR_PSBL_CSH               1155
#define IDC_CSGN_WMY_TOT_AMT            1156
#define IDC_CSGN_WMY_CSH                1157
#define IDC_MNMG_TOT_AMT                1158
#define IDC_MNMG_CSH                    1159
#define IDC_ADIT_WMY_TOT_AMT            1160
#define IDC_ADIT_WMY_CSH                1161
#define IDC_EVL_AMT                     1162
#define IDC_EVL_PFLS                    1163
#define IDC_FEE                         1164
#define IDC_RCVA                        1165
#define IDC_THDT_PFLS_AMT               1166
#define IDC_DATETIME2                   1167
#define IDC_DATETIME3                   1168
#define IDC_RD_EXE_OPT1                 1169
#define IDC_RD_EXE_OPT2                 1170
#define IDC_BTN_REQ_CUR_RATE            1170
#define IDC_RD_EXE_OPT3                 1171
#define IDC_BTN_REQ_KOSPI               1171
#define IDC_RD_EXE_SORT1                1172
#define IDC_BTN_REQ_CUR_RATE2           1172
#define IDC_BTN_REQ_MEM                 1172
#define IDC_RD_EXE_SORT2                1173
#define IDC_RD_BAL_OPT1                 1174
#define IDC_RD_BAL_OPT2                 1175
#define IDC_RD_DEP_OPT1                 1176
#define IDC_RD_FO_OPT1                  1176
#define IDC_RD_DEP_OPT2                 1177
#define IDC_RD_FO_OPT2                  1177
#define IDC_RD_FO_OPT3                  1178
#define IDC_RD_SB1                      1179
#define IDC_RD_SB2                      1180
#define IDC_RD_SB3                      1181
#define IDC_BTN_ACCINFO                 1181
#define IDC_BUTTON2                     1182
#define IDC_BTN_MEM_RANK                1184
#define IDC_RADIO_EX1                   1185
#define IDC_RADIO_EX2                   1186
#define IDC_POS_SELLBUY                 1187
#define IDC_BUTTON_REAL                 1188
#define IDC_RAD_QRY1                    1189
#define IDC_RAD_QRY2                    1190
#define IDC_BUTTON_TEST                 1190
#define IDC_RAD_QRY3                    1191
#define IDC_RADIO_KOSPI                 1191
#define IDC_RAD_QRY4                    1192
#define IDC_RADIO_KOSDAQ                1192
#define IDC_BTN_REQ_MASTER              1192
#define IDC_RAD_QRY5                    1193
#define IDC_RADIO_KOSPI200              1193
#define IDC_BTN_REQ_CODE                1193
#define IDC_RAD_QRY6                    1194
#define IDC_RADIO_KRX                   1194
#define IDC_LIST_CODE                   1194
#define IDC_RAD_QRY7                    1195
#define IDC_RAD_QRY8                    1196
#define IDC_CHECK_MINI                  1197

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1195
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
